services:
  - type: web
    name: blackcube-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: REFRESH_EXPIRES_IN
        value: 7d
